version: '3.8'

services:
  firstservice:
    image: com.microframe-first-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "firstservice"
networks:
  backend:
    driver: bridge
