package com.microframe.second.service

import com.microframe.second.model.SecondServiceModel
import com.microframe.second.repository.SecondRepository
import io.github.resilience4j.bulkhead.annotation.Bulkhead
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.context.MessageSource
import org.springframework.stereotype.Service
import java.util.*

@Service
open class SecondService {
    @Autowired
    lateinit var messages: MessageSource
    @Autowired
    lateinit var secondRepository: SecondRepository

    //Breaker for the db interaction
    @CircuitBreaker(name = "secondServiceInternalCBreaker",
                fallbackMethod= "getSecondFallback")
    @Bulkhead(name = "secondServiceInternalBulkhead",
        fallbackMethod= "getSecondFallback")
    fun getSecond(secondName: String, locale: Locale): SecondServiceModel {
        var fm: SecondServiceModel? = secondRepository.findBySecondName(secondName)
        fm?.let {
            return it
        }
        throw IllegalArgumentException(
            String.format(messages.getMessage(
                "second.search.error.message", null, locale), secondName));
    }

    private fun getSecondFallback(secondName: String, locale: Locale, @Suppress("UNUSED_PARAMETER") t: Throwable): SecondServiceModel {
        var fm = SecondServiceModel()
        fm.let {
            it.secondName = secondName
            it.description = "This instance was generated by a fallback method, it is not possible to get the service instance from the database. (Locale[${locale.displayName}])"
        }
        return fm
    }

    fun createSecond(second: SecondServiceModel, locale: Locale):SecondServiceModel {
        second.apply {
            secondName = when(secondName) {
                "" -> String.format("secondName_%s", UUID.randomUUID().toString().dropLast(20))
                else -> {
                    secondName
                }
            }
        }
        secondRepository.save(second)
        return second
    }

    fun updateSecond(second: SecondServiceModel, locale: Locale):SecondServiceModel {
        secondRepository.save(second)
        return second
    }

    fun deleteSecond(secondName: String, locale: Locale):String {
        var secondForDel = secondRepository.findBySecondName(secondName)
        var responseMessage = String.format(messages.getMessage("second.delete.message", null, locale),
            secondForDel?.id, secondForDel?.secondName)
        secondRepository.deleteBySecondName(secondName)
        return responseMessage
    }
}